title: OptimexEcuador
description: Optica Optimex
url: "https://optimexecuador.com"
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md
  - services.md
  - contact.md
